### PR TITLE
Override package archs for armv7

### PR DESCRIPTION
**Pull request by ghost**
As described in #6, there are ARM-based Synology devices that need the package arch to be set to the according platform. To extend the arch field automatically I hacked together a small script that overrides the arch list for armv7. It can be used to extend other packages in the future if required. For now I added `armadaxp`, `armada375` and `armada38x` as they were reported to work fine by @rvalle, @PaulLebmann and me.

Please let me know what you think about it!

### CODE REVIEW

**Comment by calmh** [comment]
Hi! Thanks! This is kinda neat, and I approve of the "let just override their arch list" concept. I'd suggest hooking it in a bit earlier in the package build if possible, rather than unpacking and modifying the final product.

The info file is created by `syncthing/INFO.sh` which currently just does `arch="$(pkg_get_unified_platform)"` which is the default operation from Synology. This INFO.sh script is run from `syncthing/SynoBuildConf/install` which is in turn run by the `pkgscripts-ng/PkgCreate.py` script from my `build-in-docker.sh`, if I remember correctly.

Perhaps we can make `INFO.sh` look for the magic env var, and set it in `build-in-docker.sh` prior to calling `PkgCreate.py`, and things would magically work through the regular pipeline?

**Comment by ghost** [comment]
@calmh I probably should have looked into how the packaging is actually working. I assumed the generation of the INFO is hidden somewhere in the Synology tooling. Your proposal is indeed much better. Please have a look at my updated branch.

**Review by calmh — APPROVED** [review]

**Comment by calmh** [comment]
Thanks, looks good.

**Comment by rvalle** [comment]
@fri-sch thanks for the patch! will try replacing my manual package with next one.

**Pull request merged**
